# Generated by Django 5.1 on 2024-08-31 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('due_date', models.DateField(default=datetime.date.today)),
                ('priority', models.CharField(default='Low', max_length=10)),
                ('details', models.TextField(blank=True, null=True)),
                ('completed', models.CharField(default='not completed', max_length=15)),
            ],
        ),
    ]
